"use client";

import React, { useState, useRef, useEffect } from 'react';
import { Button } from '@/components/ui/button';
import { Popover, PopoverContent, PopoverTrigger } from '@/components/ui/popover';
import { Input } from '@/components/ui/input';
import { ScrollArea } from '@/components/ui/scroll-area';
import { Smile, Search } from 'lucide-react';
import { cn } from '@/lib/utils';

// Emoji categories and data
const emojiCategories = [
  {
    name: 'Smileys & Emotion',
    icon: '😀',
    emojis: [
      { emoji: '😀', keywords: ['grinning', 'face', 'smile', 'happy', 'joy'] },
      { emoji: '😃', keywords: ['grinning', 'face', 'big', 'eyes', 'smile', 'happy', 'joy'] },
      { emoji: '😄', keywords: ['grinning', 'face', 'smiling', 'eyes', 'happy', 'joy'] },
      { emoji: '😁', keywords: ['grinning', 'face', 'smiling', 'eyes', 'teeth', 'happy'] },
      { emoji: '😆', keywords: ['grinning', 'face', 'squinting', 'teeth', 'happy', 'joy'] },
      { emoji: '😅', keywords: ['grinning', 'face', 'sweat', 'smile', 'relief'] },
      { emoji: '😂', keywords: ['face', 'tears', 'joy', 'laughing', 'crying', 'happy'] },
      { emoji: '🤣', keywords: ['rolling', 'laughing', 'face', 'joy', 'funny', 'laugh'] },
      { emoji: '😊', keywords: ['smiling', 'face', 'smiling', 'eyes', 'blush', 'happy'] },
      { emoji: '😇', keywords: ['smiling', 'face', 'halo', 'innocent', 'angel', 'good'] },
      { emoji: '🙂', keywords: ['slightly', 'smiling', 'face', 'smile', 'happy'] },
      { emoji: '🙃', keywords: ['upside', 'down', 'face', 'silly', 'funny'] },
      { emoji: '😉', keywords: ['winking', 'face', 'wink', 'playful', 'flirt'] },
      { emoji: '😌', keywords: ['relieved', 'face', 'relief', 'peaceful', 'calm'] },
      { emoji: '😍', keywords: ['smiling', 'face', 'heart', 'eyes', 'love', 'adore'] },
      { emoji: '🥰', keywords: ['smiling', 'face', 'hearts', 'love', 'adore', 'romance'] },
      { emoji: '😘', keywords: ['face', 'blowing', 'kiss', 'love', 'romance'] },
      { emoji: '😗', keywords: ['kissing', 'face', 'kiss', 'love', 'romance'] },
      { emoji: '😙', keywords: ['kissing', 'face', 'smiling', 'eyes', 'kiss', 'love'] },
      { emoji: '😚', keywords: ['kissing', 'face', 'closed', 'eyes', 'kiss', 'love'] },
      { emoji: '😋', keywords: ['face', 'savoring', 'food', 'yummy', 'delicious'] },
      { emoji: '😛', keywords: ['face', 'tongue', 'silly', 'funny', 'playful'] },
      { emoji: '😝', keywords: ['face', 'tongue', 'squinting', 'silly', 'funny'] },
      { emoji: '😜', keywords: ['face', 'tongue', 'winking', 'silly', 'funny'] },
      { emoji: '🤪', keywords: ['zany', 'face', 'silly', 'crazy', 'funny'] },
      { emoji: '🤨', keywords: ['face', 'raised', 'eyebrow', 'skeptical', 'doubt'] },
      { emoji: '🧐', keywords: ['face', 'monocle', 'curious', 'investigating', 'detective'] },
      { emoji: '🤓', keywords: ['nerd', 'face', 'glasses', 'smart', 'intelligent'] },
      { emoji: '😎', keywords: ['face', 'sunglasses', 'cool', 'awesome', 'stylish'] },
      { emoji: '🤩', keywords: ['star', 'struck', 'face', 'amazed', 'excited'] },
      { emoji: '🥳', keywords: ['partying', 'face', 'celebration', 'party', 'birthday'] },
      { emoji: '😏', keywords: ['smirking', 'face', 'smug', 'confident', 'satisfied'] },
      { emoji: '😒', keywords: ['unamused', 'face', 'bored', 'unimpressed', 'meh'] },
      { emoji: '😞', keywords: ['disappointed', 'face', 'sad', 'let', 'down'] },
      { emoji: '😔', keywords: ['pensive', 'face', 'thoughtful', 'sad', 'melancholy'] },
      { emoji: '😟', keywords: ['worried', 'face', 'concerned', 'anxious', 'nervous'] },
      { emoji: '😕', keywords: ['confused', 'face', 'unsure', 'puzzled', 'uncertain'] },
      { emoji: '🙁', keywords: ['slightly', 'frowning', 'face', 'sad', 'unhappy'] },
      { emoji: '☹️', keywords: ['frowning', 'face', 'sad', 'unhappy', 'disappointed'] },
      { emoji: '😣', keywords: ['persevering', 'face', 'struggling', 'determined', 'tired'] },
      { emoji: '😖', keywords: ['confounded', 'face', 'confused', 'frustrated', 'angry'] },
      { emoji: '😫', keywords: ['tired', 'face', 'exhausted', 'weary', 'sleepy'] },
      { emoji: '😩', keywords: ['weary', 'face', 'tired', 'exhausted', 'frustrated'] },
      { emoji: '🥺', keywords: ['pleading', 'face', 'begging', 'puppy', 'eyes', 'cute'] },
      { emoji: '😢', keywords: ['crying', 'face', 'sad', 'tears', 'sorrow'] },
      { emoji: '😭', keywords: ['loudly', 'crying', 'face', 'sad', 'tears', 'sorrow'] },
      { emoji: '😤', keywords: ['face', 'steam', 'nose', 'frustrated', 'angry'] },
      { emoji: '😠', keywords: ['angry', 'face', 'mad', 'furious', 'irritated'] },
      { emoji: '😡', keywords: ['pouting', 'face', 'angry', 'mad', 'furious'] },
      { emoji: '🤬', keywords: ['face', 'symbols', 'mouth', 'swearing', 'angry'] },
      { emoji: '🤯', keywords: ['exploding', 'head', 'mind', 'blown', 'shocked'] },
      { emoji: '😳', keywords: ['flushed', 'face', 'embarrassed', 'shocked', 'surprised'] },
      { emoji: '🥵', keywords: ['hot', 'face', 'fever', 'heat', 'sweat'] },
      { emoji: '🥶', keywords: ['cold', 'face', 'freezing', 'chilly', 'ice'] },
      { emoji: '😱', keywords: ['face', 'screaming', 'fear', 'shocked', 'horror'] },
      { emoji: '😨', keywords: ['fearful', 'face', 'scared', 'fear', 'anxious'] },
      { emoji: '😰', keywords: ['anxious', 'face', 'sweat', 'nervous', 'worried'] },
      { emoji: '😥', keywords: ['sad', 'relieved', 'face', 'disappointed', 'relief'] },
      { emoji: '😓', keywords: ['downcast', 'face', 'sweat', 'disappointed', 'relief'] },
      { emoji: '🤗', keywords: ['hugging', 'face', 'hug', 'love', 'care'] },
      { emoji: '🤔', keywords: ['thinking', 'face', 'thought', 'contemplating', 'pondering'] },
      { emoji: '🤭', keywords: ['face', 'hand', 'over', 'mouth', 'secret', 'giggle'] },
      { emoji: '🤫', keywords: ['shushing', 'face', 'quiet', 'silence', 'secret'] },
      { emoji: '🤥', keywords: ['lying', 'face', 'lie', 'dishonest', 'deceitful'] },
      { emoji: '😶', keywords: ['face', 'mouth', 'closed', 'silent', 'quiet'] },
      { emoji: '😐', keywords: ['neutral', 'face', 'expressionless', 'blank', 'indifferent'] },
      { emoji: '😑', keywords: ['expressionless', 'face', 'blank', 'neutral', 'indifferent'] },
      { emoji: '😯', keywords: ['hushed', 'face', 'surprised', 'shocked', 'quiet'] },
      { emoji: '😦', keywords: ['frowning', 'face', 'open', 'mouth', 'sad', 'concerned'] },
      { emoji: '😧', keywords: ['anguished', 'face', 'pain', 'suffering', 'distressed'] },
      { emoji: '😮', keywords: ['face', 'open', 'mouth', 'surprised', 'shocked'] },
      { emoji: '😲', keywords: ['astonished', 'face', 'surprised', 'shocked', 'amazed'] },
      { emoji: '🥱', keywords: ['yawning', 'face', 'tired', 'sleepy', 'bored'] },
      { emoji: '😴', keywords: ['sleeping', 'face', 'sleep', 'tired', 'rest'] },
      { emoji: '🤤', keywords: ['drooling', 'face', 'hungry', 'desire', 'food'] },
      { emoji: '😪', keywords: ['sleepy', 'face', 'tired', 'sleep', 'exhausted'] },
      { emoji: '😵', keywords: ['dizzy', 'face', 'confused', 'spinning', 'woozy'] },
      { emoji: '🤐', keywords: ['zipper', 'mouth', 'face', 'silent', 'secret'] },
      { emoji: '🥴', keywords: ['woozy', 'face', 'dizzy', 'confused', 'drunk'] },
      { emoji: '🤢', keywords: ['nauseated', 'face', 'sick', 'ill', 'disgusted'] },
      { emoji: '🤮', keywords: ['face', 'vomiting', 'sick', 'ill', 'nauseated'] },
      { emoji: '🤧', keywords: ['face', 'sneezing', 'sick', 'cold', 'allergy'] },
      { emoji: '😷', keywords: ['face', 'medical', 'mask', 'sick', 'ill', 'health'] },
      { emoji: '🤒', keywords: ['face', 'thermometer', 'sick', 'ill', 'fever'] },
      { emoji: '🤕', keywords: ['face', 'bandage', 'injured', 'hurt', 'wound'] },
      { emoji: '🤑', keywords: ['money', 'mouth', 'face', 'rich', 'wealth', 'greedy'] },
      { emoji: '🤠', keywords: ['cowboy', 'hat', 'face', 'western', 'country'] },
      { emoji: '💩', keywords: ['pile', 'poo', 'face', 'poop', 'funny', 'silly'] },
      { emoji: '👻', keywords: ['ghost', 'face', 'spooky', 'halloween', 'scary'] },
      { emoji: '💀', keywords: ['skull', 'death', 'dead', 'danger', 'poison'] },
      { emoji: '☠️', keywords: ['skull', 'crossbones', 'death', 'danger', 'poison'] },
      { emoji: '👽', keywords: ['alien', 'face', 'extraterrestrial', 'ufo', 'space'] },
      { emoji: '👾', keywords: ['alien', 'monster', 'game', 'arcade', 'space'] },
      { emoji: '🤖', keywords: ['robot', 'face', 'android', 'technology', 'machine'] },
      { emoji: '😺', keywords: ['grinning', 'cat', 'face', 'smile', 'happy', 'feline'] },
      { emoji: '😸', keywords: ['grinning', 'cat', 'face', 'smiling', 'eyes', 'happy'] },
      { emoji: '😹', keywords: ['cat', 'face', 'tears', 'joy', 'laughing', 'crying'] },
      { emoji: '😻', keywords: ['smiling', 'cat', 'face', 'heart', 'eyes', 'love'] },
      { emoji: '😼', keywords: ['cat', 'face', 'wry', 'smile', 'sly', 'mischievous'] },
      { emoji: '😽', keywords: ['kissing', 'cat', 'face', 'kiss', 'love', 'romance'] },
      { emoji: '🙀', keywords: ['cat', 'face', 'screaming', 'fear', 'shocked', 'horror'] },
      { emoji: '😿', keywords: ['crying', 'cat', 'face', 'sad', 'tears', 'sorrow'] },
      { emoji: '😾', keywords: ['pouting', 'cat', 'face', 'angry', 'mad', 'furious'] },
      { emoji: '🙈', keywords: ['see', 'no', 'evil', 'monkey', 'face', 'hands'] },
      { emoji: '🙉', keywords: ['hear', 'no', 'evil', 'monkey', 'face', 'hands'] },
      { emoji: '🙊', keywords: ['speak', 'no', 'evil', 'monkey', 'face', 'hands'] },
      { emoji: '👶', keywords: ['baby', 'child', 'infant', 'young', 'cute'] },
      { emoji: '👧', keywords: ['girl', 'child', 'young', 'female', 'kid'] },
      { emoji: '🧒', keywords: ['child', 'young', 'kid', 'boy', 'girl'] },
      { emoji: '👦', keywords: ['boy', 'child', 'young', 'male', 'kid'] },
      { emoji: '👩', keywords: ['woman', 'adult', 'female', 'person', 'human'] },
      { emoji: '🧑', keywords: ['person', 'adult', 'human', 'neutral', 'gender'] },
      { emoji: '👨', keywords: ['man', 'adult', 'male', 'person', 'human'] },
      { emoji: '👵', keywords: ['old', 'woman', 'elderly', 'female', 'senior'] },
      { emoji: '🧓', keywords: ['old', 'person', 'elderly', 'senior', 'adult'] },
      { emoji: '👴', keywords: ['old', 'man', 'elderly', 'male', 'senior'] },
      { emoji: '👮‍♀️', keywords: ['woman', 'police', 'officer', 'law', 'enforcement'] },
      { emoji: '👮', keywords: ['police', 'officer', 'law', 'enforcement', 'cop'] },
      { emoji: '👮‍♂️', keywords: ['man', 'police', 'officer', 'law', 'enforcement'] },
      { emoji: '🕵️‍♀️', keywords: ['woman', 'detective', 'spy', 'investigation', 'sleuth'] },
      { emoji: '🕵️', keywords: ['detective', 'spy', 'investigation', 'sleuth', 'private'] },
      { emoji: '🕵️‍♂️', keywords: ['man', 'detective', 'spy', 'investigation', 'sleuth'] },
      { emoji: '💂‍♀️', keywords: ['woman', 'guard', 'security', 'protection', 'defense'] },
      { emoji: '💂', keywords: ['guard', 'security', 'protection', 'defense', 'soldier'] },
      { emoji: '💂‍♂️', keywords: ['man', 'guard', 'security', 'protection', 'defense'] },
      { emoji: '👷‍♀️', keywords: ['woman', 'construction', 'worker', 'builder', 'hardhat'] },
      { emoji: '👷', keywords: ['construction', 'worker', 'builder', 'hardhat', 'labor'] },
      { emoji: '👷‍♂️', keywords: ['man', 'construction', 'worker', 'builder', 'hardhat'] },
      { emoji: '🤴', keywords: ['prince', 'royal', 'crown', 'noble', 'royalty'] },
      { emoji: '👸', keywords: ['princess', 'royal', 'crown', 'noble', 'royalty'] },
      { emoji: '👳‍♀️', keywords: ['woman', 'turban', 'headscarf', 'cultural', 'religious'] },
      { emoji: '👳', keywords: ['person', 'turban', 'headscarf', 'cultural', 'religious'] },
      { emoji: '👳‍♂️', keywords: ['man', 'turban', 'headscarf', 'cultural', 'religious'] },
      { emoji: '👲', keywords: ['person', 'skullcap', 'hat', 'cultural', 'traditional'] },
      { emoji: '🧕', keywords: ['woman', 'headscarf', 'hijab', 'cultural', 'religious'] },
      { emoji: '🤵‍♀️', keywords: ['woman', 'tuxedo', 'formal', 'wedding', 'elegant'] },
      { emoji: '🤵', keywords: ['person', 'tuxedo', 'formal', 'wedding', 'elegant'] },
      { emoji: '🤵‍♂️', keywords: ['man', 'tuxedo', 'formal', 'wedding', 'elegant'] },
      { emoji: '👰‍♀️', keywords: ['woman', 'veil', 'wedding', 'bride', 'marriage'] },
      { emoji: '👰', keywords: ['person', 'veil', 'wedding', 'bride', 'marriage'] },
      { emoji: '👰‍♂️', keywords: ['man', 'veil', 'wedding', 'groom', 'marriage'] }
    ]
  },
  {
    name: 'Animals & Nature',
    icon: '🐶',
    emojis: [
      { emoji: '🐶', keywords: ['dog', 'puppy', 'pet', 'animal'] },
      { emoji: '🐱', keywords: ['cat', 'kitten', 'pet', 'animal'] },
      { emoji: '🐭', keywords: ['mouse', 'rodent', 'animal'] },
      { emoji: '🐹', keywords: ['hamster', 'pet', 'animal'] },
      { emoji: '🐰', keywords: ['rabbit', 'bunny', 'pet', 'animal'] },
      { emoji: '🦊', keywords: ['fox', 'animal'] },
      { emoji: '🐻', keywords: ['bear', 'animal'] },
      { emoji: '🐼', keywords: ['panda', 'animal'] },
      { emoji: '🐨', keywords: ['koala', 'animal'] },
      { emoji: '🐯', keywords: ['tiger', 'animal'] },
      { emoji: '🦁', keywords: ['lion', 'animal'] },
      { emoji: '🐮', keywords: ['cow', 'animal'] },
      { emoji: '🐷', keywords: ['pig', 'animal'] },
      { emoji: '🐸', keywords: ['frog', 'animal'] },
      { emoji: '🐵', keywords: ['monkey', 'animal'] },
      { emoji: '🙈', keywords: ['see', 'no', 'evil', 'monkey', 'face', 'hands'] },
      { emoji: '🙉', keywords: ['hear', 'no', 'evil', 'monkey', 'face', 'hands'] },
      { emoji: '🙊', keywords: ['speak', 'no', 'evil', 'monkey', 'face', 'hands'] },
      { emoji: '🐒', keywords: ['monkey', 'animal'] },
      { emoji: '🐔', keywords: ['chicken', 'animal'] },
      { emoji: '🐧', keywords: ['penguin', 'animal'] },
      { emoji: '🐦', keywords: ['bird', 'animal'] },
      { emoji: '🐤', keywords: ['chick', 'animal'] },
      { emoji: '🐣', keywords: ['egg', 'animal'] },
      { emoji: '🐥', keywords: ['hatchling', 'animal'] },
      { emoji: '🦆', keywords: ['duck', 'animal'] },
      { emoji: '🦅', keywords: ['eagle', 'animal'] },
      { emoji: '🦉', keywords: ['owl', 'animal'] },
      { emoji: '🦇', keywords: ['bat', 'animal'] },
      { emoji: '🐺', keywords: ['wolf', 'animal'] },
      { emoji: '🐗', keywords: ['boar', 'animal'] },
      { emoji: '🐴', keywords: ['horse', 'animal'] },
      { emoji: '🦄', keywords: ['unicorn', 'animal'] },
      { emoji: '🐝', keywords: ['bee', 'animal'] },
      { emoji: '🐛', keywords: ['bug', 'animal'] },
      { emoji: '🦋', keywords: ['butterfly', 'animal'] },
      { emoji: '🐌', keywords: ['snail', 'animal'] },
      { emoji: '🐞', keywords: ['ladybug', 'animal'] },
      { emoji: '🐜', keywords: ['ant', 'animal'] },
      { emoji: '🦟', keywords: ['mosquito', 'animal'] },
      { emoji: '🦗', keywords: ['cricket', 'animal'] },
      { emoji: '🕷️', keywords: ['spider', 'animal'] },
      { emoji: '🕸️', keywords: ['web', 'animal'] },
      { emoji: '🦂', keywords: ['scorpion', 'animal'] },
      { emoji: '🐢', keywords: ['tortoise', 'animal'] },
      { emoji: '🐍', keywords: ['snake', 'animal'] },
      { emoji: '🦎', keywords: ['lizard', 'animal'] },
      { emoji: '🦖', keywords: ['dinosaur', 'animal'] },
      { emoji: '🦕', keywords: ['triceratops', 'animal'] },
      { emoji: '🐙', keywords: ['octopus', 'animal'] },
      { emoji: '🦑', keywords: ['squid', 'animal'] },
      { emoji: '🦐', keywords: ['shrimp', 'animal'] },
      { emoji: '🦞', keywords: ['lobster', 'animal'] },
      { emoji: '🦀', keywords: ['crab', 'animal'] },
      { emoji: '🐡', keywords: ['blowfish', 'animal'] },
      { emoji: '🐠', keywords: ['tropical fish', 'animal'] },
      { emoji: '🐟', keywords: ['fish', 'animal'] },
      { emoji: '🐬', keywords: ['dolphin', 'animal'] },
      { emoji: '🐳', keywords: ['whale', 'animal'] },
      { emoji: '🐋', keywords: ['whale', 'animal'] },
      { emoji: '🦈', keywords: ['shark', 'animal'] },
      { emoji: '🐊', keywords: ['crocodile', 'animal'] },
      { emoji: '🐅', keywords: ['tiger', 'animal'] },
      { emoji: '🐆', keywords: ['leopard', 'animal'] },
      { emoji: '🦓', keywords: ['zebra', 'animal'] },
      { emoji: '🦍', keywords: ['gorilla', 'animal'] },
      { emoji: '🦧', keywords: ['orangutan', 'animal'] },
      { emoji: '🐘', keywords: ['elephant', 'animal'] },
      { emoji: '🦛', keywords: ['rhino', 'animal'] },
      { emoji: '🦏', keywords: ['hippo', 'animal'] },
      { emoji: '🐪', keywords: ['camel', 'animal'] },
      { emoji: '🐫', keywords: ['dromedary', 'animal'] },
      { emoji: '🦙', keywords: ['llama', 'animal'] },
      { emoji: '🦒', keywords: ['giraffe', 'animal'] },
      { emoji: '🐃', keywords: ['bison', 'animal'] },
      { emoji: '🐂', keywords: ['ox', 'animal'] },
      { emoji: '🐄', keywords: ['cow', 'animal'] },
      { emoji: '🐎', keywords: ['horse', 'animal'] },
      { emoji: '🐖', keywords: ['pig', 'animal'] },
      { emoji: '🐏', keywords: ['ram', 'animal'] },
      { emoji: '🐑', keywords: ['sheep', 'animal'] },
      { emoji: '🐐', keywords: ['donkey', 'animal'] },
      { emoji: '🦌', keywords: ['deer', 'animal'] },
      { emoji: '🐕', keywords: ['dog', 'pet'] },
      { emoji: '🐩', keywords: ['poodle', 'dog'] },
      { emoji: '🦮', keywords: ['guide dog', 'dog'] },
      { emoji: '🐕‍🦺', keywords: ['service dog', 'dog'] },
      { emoji: '🐈', keywords: ['cat', 'pet'] },
      { emoji: '🐈‍⬛', keywords: ['black cat', 'cat'] },
      { emoji: '🐓', keywords: ['rooster', 'animal'] },
      { emoji: '🦃', keywords: ['turkey', 'animal'] },
      { emoji: '🦚', keywords: ['peacock', 'animal'] },
      { emoji: '🦜', keywords: ['parrot', 'animal'] },
      { emoji: '🦢', keywords: ['swan', 'animal'] },
      { emoji: '🦩', keywords: ['flamingo', 'animal'] },
      { emoji: '🕊️', keywords: ['dove', 'animal'] },
      { emoji: '🐇', keywords: ['rabbit', 'pet'] },
      { emoji: '🦝', keywords: ['raccoon', 'animal'] },
      { emoji: '🦨', keywords: ['skunk', 'animal'] },
      { emoji: '🦡', keywords: ['badger', 'animal'] },
      { emoji: '🦫', keywords: ['beaver', 'animal'] },
      { emoji: '🦦', keywords: ['seal', 'animal'] },
      { emoji: '🦥', keywords: ['otter', 'animal'] },
      { emoji: '🐁', keywords: ['mouse', 'animal'] },
      { emoji: '🐀', keywords: ['rat', 'animal'] },
      { emoji: '🐿️', keywords: ['chipmunk', 'animal'] },
      { emoji: '🦔', keywords: ['hedgehog', 'animal'] },
      { emoji: '🌵', keywords: ['cactus', 'plant'] },
      { emoji: '🎄', keywords: ['christmas tree', 'plant'] },
      { emoji: '🌲', keywords: ['forest', 'plant'] },
      { emoji: '🌳', keywords: ['tree', 'plant'] },
      { emoji: '🌴', keywords: ['palm tree', 'plant'] },
      { emoji: '🌱', keywords: ['seedling', 'plant'] },
      { emoji: '🌿', keywords: ['herb', 'plant'] },
      { emoji: '☘️', keywords: ['clover', 'plant'] },
      { emoji: '🍀', keywords: ['four leaf clover', 'plant'] },
      { emoji: '🎍', keywords: ['bamboo', 'plant'] },
      { emoji: '🎋', keywords: ['tanabata tree', 'plant'] },
      { emoji: '🍃', keywords: ['leaf', 'plant'] },
      { emoji: '🍂', keywords: ['fallen leaf', 'plant'] },
      { emoji: '🍁', keywords: ['maple leaf', 'plant'] },
      { emoji: '🍄', keywords: ['mushroom', 'plant'] },
      { emoji: '🌾', keywords: ['ear of rice', 'plant'] },
      { emoji: '💐', keywords: ['bouquet', 'plant'] },
      { emoji: '🌷', keywords: ['rose', 'flower'] },
      { emoji: '🌹', keywords: ['tulip', 'flower'] },
      { emoji: '🥀', keywords: ['wilted flower', 'flower'] },
      { emoji: '🌺', keywords: ['hibiscus', 'flower'] },
      { emoji: '🌻', keywords: ['sunflower', 'flower'] },
      { emoji: '🌼', keywords: ['blossom', 'flower'] },
      { emoji: '🌸', keywords: ['cherry blossom', 'flower'] },
      { emoji: '🌿', keywords: ['herb', 'plant'] }
    ]
  },
  {
    name: 'Food & Drink',
    icon: '🍎',
    emojis: [
      { emoji: '🍎', keywords: ['apple', 'fruit'] },
      { emoji: '🍐', keywords: ['pear', 'fruit'] },
      { emoji: '🍊', keywords: ['tangerine', 'fruit'] },
      { emoji: '🍋', keywords: ['lemon', 'fruit'] },
      { emoji: '🍌', keywords: ['banana', 'fruit'] },
      { emoji: '🍉', keywords: ['watermelon', 'fruit'] },
      { emoji: '🍇', keywords: ['grapes', 'fruit'] },
      { emoji: '🍓', keywords: ['strawberry', 'fruit'] },
      { emoji: '🫐', keywords: ['blueberries', 'fruit'] },
      { emoji: '🍈', keywords: ['melon', 'fruit'] },
      { emoji: '🍒', keywords: ['cherries', 'fruit'] },
      { emoji: '🍑', keywords: ['peach', 'fruit'] },
      { emoji: '🥭', keywords: ['mango', 'fruit'] },
      { emoji: '🍍', keywords: ['pineapple', 'fruit'] },
      { emoji: '🥥', keywords: ['coconut', 'fruit'] },
      { emoji: '🥝', keywords: ['kiwi', 'fruit'] },
      { emoji: '🍅', keywords: ['tomato', 'fruit'] },
      { emoji: '🥑', keywords: ['avocado', 'fruit'] },
      { emoji: '🥦', keywords: ['broccoli', 'vegetable'] },
      { emoji: '🥬', keywords: ['leafy green', 'vegetable'] },
      { emoji: '🥒', keywords: ['cucumber', 'vegetable'] },
      { emoji: '🌶️', keywords: ['hot pepper', 'vegetable'] },
      { emoji: '🫑', keywords: ['bell pepper', 'vegetable'] },
      { emoji: '🌽', keywords: ['corn', 'vegetable'] },
      { emoji: '🥕', keywords: ['carrot', 'vegetable'] },
      { emoji: '🫒', keywords: ['olive', 'fruit'] },
      { emoji: '🧄', keywords: ['garlic', 'vegetable'] },
      { emoji: '🧅', keywords: ['onion', 'vegetable'] },
      { emoji: '🥔', keywords: ['potato', 'vegetable'] },
      { emoji: '🍠', keywords: ['sweet potato', 'vegetable'] },
      { emoji: '🥐', keywords: ['croissant', 'food'] },
      { emoji: '🥯', keywords: ['bagel', 'food'] },
      { emoji: '🍞', keywords: ['bread', 'food'] },
      { emoji: '🥖', keywords: ['baguette', 'food'] },
      { emoji: '🥨', keywords: ['pretzel', 'food'] },
      { emoji: '🧀', keywords: ['cheese', 'food'] },
      { emoji: '🥚', keywords: ['egg', 'food'] },
      { emoji: '🍳', keywords: ['cooking', 'food'] },
      { emoji: '🧈', keywords: ['butter', 'food'] },
      { emoji: '🥞', keywords: ['pancakes', 'food'] },
      { emoji: '🧇', keywords: ['waffle', 'food'] },
      { emoji: '🥓', keywords: ['bacon', 'food'] },
      { emoji: '🥩', keywords: ['steak', 'food'] },
      { emoji: '🍗', keywords: ['chicken', 'food'] },
      { emoji: '🍖', keywords: ['meat', 'food'] },
      { emoji: '🦴', keywords: ['bone', 'food'] },
      { emoji: '🌭', keywords: ['hot dog', 'food'] },
      { emoji: '🍔', keywords: ['hamburger', 'food'] },
      { emoji: '🍟', keywords: ['french fries', 'food'] },
      { emoji: '🍕', keywords: ['pizza', 'food'] },
      { emoji: '🥪', keywords: ['sandwich', 'food'] },
      { emoji: '🥙', keywords: ['stuffed flatbread', 'food'] },
      { emoji: '🧆', keywords: ['falafel', 'food'] },
      { emoji: '🌮', keywords: ['taco', 'food'] },
      { emoji: '🌯', keywords: ['burrito', 'food'] },
      { emoji: '🫔', keywords: ['tamale', 'food'] },
      { emoji: '🥗', keywords: ['salad', 'food'] },
      { emoji: '🍲', keywords: ['stew', 'food'] },
      { emoji: '🫕', keywords: ['fondue', 'food'] },
      { emoji: '🥫', keywords: ['canned food', 'food'] },
      { emoji: '🍝', keywords: ['spaghetti', 'food'] },
      { emoji: '🍜', keywords: ['noodles', 'food'] },
      { emoji: '🍲', keywords: ['soup', 'food'] },
      { emoji: '🍛', keywords: ['curry', 'food'] },
      { emoji: '🍣', keywords: ['sushi', 'food'] },
      { emoji: '🍱', keywords: ['bento box', 'food'] },
      { emoji: '🥟', keywords: ['dumpling', 'food'] },
      { emoji: '🦪', keywords: ['oyster', 'food'] },
      { emoji: '🍤', keywords: ['shrimp', 'food'] },
      { emoji: '🍙', keywords: ['rice ball', 'food'] },
      { emoji: '🍚', keywords: ['rice', 'food'] },
      { emoji: '🍘', keywords: ['rice cracker', 'food'] },
      { emoji: '🍥', keywords: ['dango', 'food'] },
      { emoji: '🥠', keywords: ['fortune cookie', 'food'] },
      { emoji: '🥮', keywords: ['moon cake', 'food'] },
      { emoji: '🍢', keywords: ['oden', 'food'] },
      { emoji: '🍡', keywords: ['dango', 'food'] },
      { emoji: '🍧', keywords: ['shaved ice', 'food'] },
      { emoji: '🍨', keywords: ['ice cream', 'food'] },
      { emoji: '🍦', keywords: ['ice cream', 'food'] },
      { emoji: '🥧', keywords: ['pie', 'food'] },
      { emoji: '🧁', keywords: ['cupcake', 'food'] },
      { emoji: '🍰', keywords: ['cake', 'food'] },
      { emoji: '🎂', keywords: ['birthday cake', 'food'] },
      { emoji: '🍮', keywords: ['custard', 'food'] },
      { emoji: '🍭', keywords: ['lollipop', 'food'] },
      { emoji: '🍬', keywords: ['candy', 'food'] },
      { emoji: '🍫', keywords: ['chocolate bar', 'food'] },
      { emoji: '🍿', keywords: ['popcorn', 'food'] },
      { emoji: '🍪', keywords: ['cookie', 'food'] },
      { emoji: '🌰', keywords: ['chestnut', 'food'] },
      { emoji: '🥜', keywords: ['peanuts', 'food'] },
      { emoji: '🍯', keywords: ['honey', 'food'] },
      { emoji: '🥛', keywords: ['milk', 'food'] },
      { emoji: '🍼', keywords: ['baby bottle', 'food'] },
      { emoji: '🫖', keywords: ['tea', 'drink'] },
      { emoji: '☕', keywords: ['coffee', 'drink'] },
      { emoji: '🍵', keywords: ['tea', 'drink'] },
      { emoji: '🧃', keywords: ['juice', 'drink'] },
      { emoji: '🥤', keywords: ['drink', 'food'] },
      { emoji: '🧋', keywords: ['bubble tea', 'drink'] },
      { emoji: '🍶', keywords: ['sake', 'drink'] },
      { emoji: '🍺', keywords: ['beer', 'drink'] },
      { emoji: '🍷', keywords: ['wine', 'drink'] },
      { emoji: '🥂', keywords: ['champagne', 'drink'] },
      { emoji: '🥃', keywords: ['whiskey', 'drink'] },
      { emoji: '🍸', keywords: ['cocktail', 'drink'] },
      { emoji: '🍹', keywords: ['tropical drink', 'drink'] },
      { emoji: '🧉', keywords: ['mate', 'drink'] },
      { emoji: '🍾', keywords: ['bottle with popping cork', 'drink'] },
      { emoji: '🥄', keywords: ['spoon', 'food'] },
      { emoji: '🍴', keywords: ['fork and knife', 'food'] },
      { emoji: '🍽️', keywords: ['plate', 'food'] },
      { emoji: '🥣', keywords: ['bowl', 'food'] },
      { emoji: '🥡', keywords: ['takeout box', 'food'] },
      { emoji: '🥢', keywords: ['chopsticks', 'food'] },
      { emoji: '🧂', keywords: ['salt', 'food'] }
    ]
  },
  {
    name: 'Activities',
    icon: '⚽',
    emojis: [
      { emoji: '⚽', keywords: ['soccer ball', 'ball'] },
      { emoji: '🏀', keywords: ['basketball', 'ball'] },
      { emoji: '🏈', keywords: ['american football', 'ball'] },
      { emoji: '⚾', keywords: ['baseball', 'ball'] },
      { emoji: '🥎', keywords: ['softball', 'ball'] },
      { emoji: '🎾', keywords: ['tennis', 'ball'] },
      { emoji: '🏐', keywords: ['volleyball', 'ball'] },
      { emoji: '🏉', keywords: ['rugby football', 'ball'] },
      { emoji: '🥏', keywords: ['flying disc', 'ball'] },
      { emoji: '🎱', keywords: ['pool', 'ball'] },
      { emoji: '🪀', keywords: ['yo-yo', 'toy'] },
      { emoji: '🏓', keywords: ['ping pong', 'game'] },
      { emoji: '🏸', keywords: ['badminton', 'game'] },
      { emoji: '🏒', keywords: ['ice hockey', 'game'] },
      { emoji: '🏑', keywords: ['field hockey', 'game'] },
      { emoji: '🥍', keywords: ['lacrosse', 'game'] },
      { emoji: '🏏', keywords: ['cricket game', 'game'] },
      { emoji: '🥅', keywords: ['goal net', 'game'] },
      { emoji: '⛳', keywords: ['golf flag', 'game'] },
      { emoji: '🪁', keywords: ['kite', 'toy'] },
      { emoji: '🏹', keywords: ['bow and arrow', 'game'] },
      { emoji: '🎣', keywords: ['fishing pole', 'game'] },
      { emoji: '🤿', keywords: ['diving mask', 'game'] },
      { emoji: '🥊', keywords: ['boxing glove', 'game'] },
      { emoji: '🥋', keywords: ['martial arts uniform', 'game'] },
      { emoji: '🎽', keywords: ['running shirt', 'game'] },
      { emoji: '🛹', keywords: ['skateboard', 'game'] },
      { emoji: '🛷', keywords: ['sled', 'game'] },
      { emoji: '⛸️', keywords: ['ice skate', 'game'] },
      { emoji: '🥌', keywords: ['curling stone', 'game'] },
      { emoji: '🎿', keywords: ['ski', 'game'] },
      { emoji: '⛷️', keywords: ['skiing', 'game'] },
      { emoji: '🏂', keywords: ['snowboard', 'game'] },
      { emoji: '🪂', keywords: ['parachute', 'game'] },
      { emoji: '🏋️‍♀️', keywords: ['woman lifting weights', 'game'] },
      { emoji: '🏋️', keywords: ['weight lifting', 'game'] },
      { emoji: '🏋️‍♂️', keywords: ['man lifting weights', 'game'] },
      { emoji: '🤼‍♀️', keywords: ['women wrestling', 'game'] },
      { emoji: '🤼', keywords: ['wrestling', 'game'] },
      { emoji: '🤼‍♂️', keywords: ['men wrestling', 'game'] },
      { emoji: '🤸‍♀️', keywords: ['woman doing push-up', 'game'] },
      { emoji: '🤸', keywords: ['push-up', 'game'] },
      { emoji: '🤸‍♂️', keywords: ['man doing push-up', 'game'] },
      { emoji: '⛹️‍♀️', keywords: ['woman playing basketball', 'game'] },
      { emoji: '⛹️', keywords: ['playing basketball', 'game'] },
      { emoji: '⛹️‍♂️', keywords: ['man playing basketball', 'game'] },
      { emoji: '🤺', keywords: ['fencer', 'game'] },
      { emoji: '🤾‍♀️', keywords: ['woman playing handball', 'game'] },
      { emoji: '🤾', keywords: ['handball', 'game'] },
      { emoji: '🤾‍♂️', keywords: ['man playing handball', 'game'] },
      { emoji: '🏊‍♀️', keywords: ['woman swimming', 'game'] },
      { emoji: '🏊', keywords: ['swimming', 'game'] },
      { emoji: '🏊‍♂️', keywords: ['man swimming', 'game'] },
      { emoji: '🚣‍♀️', keywords: ['woman rowing boat', 'game'] },
      { emoji: '🚣', keywords: ['rowing', 'game'] },
      { emoji: '🚣‍♂️', keywords: ['man rowing boat', 'game'] },
      { emoji: '🧗‍♀️', keywords: ['woman climbing', 'game'] },
      { emoji: '🧗', keywords: ['climbing', 'game'] },
      { emoji: '🧗‍♂️', keywords: ['man climbing', 'game'] },
      { emoji: '🚵‍♀️', keywords: ['woman mountain biking', 'game'] },
      { emoji: '🚵', keywords: ['mountain biking', 'game'] },
      { emoji: '🚵‍♂️', keywords: ['man mountain biking', 'game'] },
      { emoji: '🚴‍♀️', keywords: ['woman bicycling', 'game'] },
      { emoji: '🚴', keywords: ['bicycling', 'game'] },
      { emoji: '🚴‍♂️', keywords: ['man bicycling', 'game'] },
      { emoji: '🏆', keywords: ['trophy', 'game'] },
      { emoji: '🥇', keywords: ['gold medal', 'game'] },
      { emoji: '🥈', keywords: ['silver medal', 'game'] },
      { emoji: '🥉', keywords: ['bronze medal', 'game'] },
      { emoji: '🏅', keywords: ['medal', 'game'] },
      { emoji: '🎖️', keywords: ['military medal', 'game'] },
      { emoji: '🏵️', keywords: ['rosette', 'game'] },
      { emoji: '🎗️', keywords: ['ribbon', 'game'] },
      { emoji: '🎫', keywords: ['ticket', 'game'] },
      { emoji: '🎟️', keywords: ['admission ticket', 'game'] },
      { emoji: '🎪', keywords: ['circus tent', 'game'] },
      { emoji: '🤹‍♀️', keywords: ['woman juggling', 'game'] },
      { emoji: '🤹', keywords: ['juggling', 'game'] },
      { emoji: '🤹‍♂️', keywords: ['man juggling', 'game'] },
      { emoji: '🎭', keywords: ['performing arts', 'game'] },
      { emoji: '🩰', keywords: ['ballet shoes', 'game'] },
      { emoji: '🎨', keywords: ['art', 'game'] },
      { emoji: '🎬', keywords: ['clapper board', 'game'] },
      { emoji: '🎤', keywords: ['microphone', 'game'] },
      { emoji: '🎧', keywords: ['headphones', 'game'] },
      { emoji: '🎼', keywords: ['musical score', 'game'] },
      { emoji: '🎹', keywords: ['piano', 'game'] },
      { emoji: '🥁', keywords: ['drum', 'game'] },
      { emoji: '🪘', keywords: ['triangle', 'game'] },
      { emoji: '🎷', keywords: ['saxophone', 'game'] },
      { emoji: '🎺', keywords: ['trumpet', 'game'] },
      { emoji: '🎸', keywords: ['guitar', 'game'] },
      { emoji: '🪕', keywords: ['banjo', 'game'] },
      { emoji: '🎻', keywords: ['violin', 'game'] },
      { emoji: '🎲', keywords: ['dice', 'game'] },
      { emoji: '♟️', keywords: ['chess pawn', 'game'] },
      { emoji: '🎯', keywords: ['dartboard', 'game'] },
      { emoji: '🎳', keywords: ['bowling', 'game'] },
      { emoji: '🎮', keywords: ['video game', 'game'] },
      { emoji: '🎰', keywords: ['slot machine', 'game'] },
      { emoji: '🧩', keywords: ['jigsaw puzzle', 'game'] },
      { emoji: '🎨', keywords: ['art', 'game'] },
      { emoji: '🎭', keywords: ['performing arts', 'game'] },
      { emoji: '🎪', keywords: ['circus tent', 'game'] },
      { emoji: '🎟️', keywords: ['admission ticket', 'game'] },
      { emoji: '🎫', keywords: ['ticket', 'game'] },
      { emoji: '🎖️', keywords: ['military medal', 'game'] },
      { emoji: '🏆', keywords: ['trophy', 'game'] },
      { emoji: '🥇', keywords: ['gold medal', 'game'] },
      { emoji: '🥈', keywords: ['silver medal', 'game'] },
      { emoji: '🥉', keywords: ['bronze medal', 'game'] },
      { emoji: '🏅', keywords: ['medal', 'game'] },
      { emoji: '🎗️', keywords: ['ribbon', 'game'] },
      { emoji: '🏵️', keywords: ['rosette', 'game'] }
    ]
  },
  {
    name: 'Travel & Places',
    icon: '🚗',
    emojis: [
      { emoji: '🚗', keywords: ['car', 'vehicle'] },
      { emoji: '🚕', keywords: ['taxi', 'vehicle'] },
      { emoji: '🚙', keywords: ['police car', 'vehicle'] },
      { emoji: '🚌', keywords: ['bus', 'vehicle'] },
      { emoji: '🚎', keywords: ['oncoming bus', 'vehicle'] },
      { emoji: '🏎️', keywords: ['racing car', 'vehicle'] },
      { emoji: '🚓', keywords: ['fire engine', 'vehicle'] },
      { emoji: '🚑', keywords: ['ambulance', 'vehicle'] },
      { emoji: '🚒', keywords: ['police car', 'vehicle'] },
      { emoji: '🚐', keywords: ['minivan', 'vehicle'] },
      { emoji: '🚚', keywords: ['delivery truck', 'vehicle'] },
      { emoji: '🚛', keywords: ['articulated lorry', 'vehicle'] },
      { emoji: '🚜', keywords: ['tractor', 'vehicle'] },
      { emoji: '🛴', keywords: ['kick scooter', 'vehicle'] },
      { emoji: '🛵', keywords: ['motor scooter', 'vehicle'] },
      { emoji: '🏍️', keywords: ['motorcycle', 'vehicle'] },
      { emoji: '🛺', keywords: ['auto rickshaw', 'vehicle'] },
      { emoji: '🚔', keywords: ['oncoming police car', 'vehicle'] },
      { emoji: '🚍', keywords: ['oncoming bus', 'vehicle'] },
      { emoji: '🚘', keywords: ['car', 'vehicle'] },
      { emoji: '🚖', keywords: ['oncoming car', 'vehicle'] },
      { emoji: '🚡', keywords: ['tram', 'vehicle'] },
      { emoji: '🚠', keywords: ['mountain cableway', 'vehicle'] },
      { emoji: '🚟', keywords: ['suspension railway', 'vehicle'] },
      { emoji: '🚃', keywords: ['train', 'vehicle'] },
      { emoji: '🚋', keywords: ['light rail vehicle', 'vehicle'] },
      { emoji: '🚞', keywords: ['mountain railway', 'vehicle'] },
      { emoji: '🚝', keywords: ['monorail', 'vehicle'] },
      { emoji: '🚄', keywords: ['high-speed train', 'vehicle'] },
      { emoji: '🚅', keywords: ['high-speed train with bullet nose', 'vehicle'] },
      { emoji: '🚈', keywords: ['passenger train', 'vehicle'] },
      { emoji: '🚂', keywords: ['locomotive', 'vehicle'] },
      { emoji: '🚆', keywords: ['train', 'vehicle'] },
      { emoji: '🚇', keywords: ['metro', 'vehicle'] },
      { emoji: '🚊', keywords: ['tram car', 'vehicle'] },
      { emoji: '🚉', keywords: ['station', 'vehicle'] },
      { emoji: '✈️', keywords: ['airplane', 'vehicle'] },
      { emoji: '🛫', keywords: ['airplane departure', 'vehicle'] },
      { emoji: '🛬', keywords: ['airplane arrival', 'vehicle'] },
      { emoji: '🛩️', keywords: ['small airplane', 'vehicle'] },
      { emoji: '💺', keywords: ['seat', 'vehicle'] },
      { emoji: '🛰️', keywords: ['satellite', 'vehicle'] },
      { emoji: '🚀', keywords: ['rocket', 'vehicle'] },
      { emoji: '🛸', keywords: ['flying saucer', 'vehicle'] },
      { emoji: '🚁', keywords: ['helicopter', 'vehicle'] },
      { emoji: '🛶', keywords: ['canoe', 'vehicle'] },
      { emoji: '⛵', keywords: ['sailboat', 'vehicle'] },
      { emoji: '🚤', keywords: ['speedboat', 'vehicle'] },
      { emoji: '🛥️', keywords: ['motor boat', 'vehicle'] },
      { emoji: '🛳️', keywords: ['passenger ship', 'vehicle'] },
      { emoji: '⛴️', keywords: ['ferry', 'vehicle'] },
      { emoji: '🚢', keywords: ['ship', 'vehicle'] },
      { emoji: '⚓', keywords: ['anchor', 'vehicle'] },
      { emoji: '🚧', keywords: ['construction', 'vehicle'] },
      { emoji: '⛽', keywords: ['fuel pump', 'vehicle'] },
      { emoji: '🚏', keywords: ['bus stop', 'vehicle'] },
      { emoji: '🚦', keywords: ['traffic light', 'vehicle'] },
      { emoji: '🚥', keywords: ['horizontal traffic light', 'vehicle'] },
      { emoji: '🗺️', keywords: ['world map', 'vehicle'] },
      { emoji: '🗿', keywords: ['moyai', 'vehicle'] },
      { emoji: '🗽', keywords: ['statue of liberty', 'vehicle'] },
      { emoji: '🗼', keywords: ['tokyo tower', 'vehicle'] },
      { emoji: '🏰', keywords: ['castle', 'vehicle'] },
      { emoji: '🏯', keywords: ['japanese castle', 'vehicle'] },
      { emoji: '🏟️', keywords: ['stadium', 'vehicle'] },
      { emoji: '🎡', keywords: ['carousel', 'vehicle'] },
      { emoji: '🎢', keywords: ['roller coaster', 'vehicle'] },
      { emoji: '🎠', keywords: ['carousel horse', 'vehicle'] },
      { emoji: '⛲', keywords: ['fountain', 'vehicle'] },
      { emoji: '⛱️', keywords: ['umbrella on ground', 'vehicle'] },
      { emoji: '🏖️', keywords: ['beach with umbrella', 'vehicle'] },
      { emoji: '🏝️', keywords: ['desert island', 'vehicle'] },
      { emoji: '🏔️', keywords: ['snow capped mountain', 'vehicle'] },
      { emoji: '🗻', keywords: ['mount fuji', 'vehicle'] },
      { emoji: '🌋', keywords: ['volcano', 'vehicle'] },
      { emoji: '🗾', keywords: ['japan flag', 'vehicle'] },
      { emoji: '🏕️', keywords: ['camping', 'vehicle'] },
      { emoji: '⛺', keywords: ['tent', 'vehicle'] },
      { emoji: '🏠', keywords: ['house', 'vehicle'] },
      { emoji: '🏡', keywords: ['house with garden', 'vehicle'] },
      { emoji: '🏘️', keywords: ['houses', 'vehicle'] },
      { emoji: '🏚️', keywords: ['empty house', 'vehicle'] },
      { emoji: '🏗️', keywords: ['building construction', 'vehicle'] },
      { emoji: '🏭', keywords: ['factory', 'vehicle'] },
      { emoji: '🏢', keywords: ['office building', 'vehicle'] },
      { emoji: '🏬', keywords: ['department store', 'vehicle'] },
      { emoji: '🏣', keywords: ['post office', 'vehicle'] },
      { emoji: '🏤', keywords: ['police station', 'vehicle'] },
      { emoji: '🏥', keywords: ['hospital', 'vehicle'] },
      { emoji: '🏦', keywords: ['bank', 'vehicle'] },
      { emoji: '🏨', keywords: ['hotel', 'vehicle'] },
      { emoji: '🏪', keywords: ['convenience store', 'vehicle'] },
      { emoji: '🏫', keywords: ['school', 'vehicle'] },
      { emoji: '🏩', keywords: ['love hotel', 'vehicle'] },
      { emoji: '💒', keywords: ['wedding', 'vehicle'] },
      { emoji: '⛪', keywords: ['church', 'vehicle'] },
      { emoji: '🕌', keywords: ['mosque', 'vehicle'] },
      { emoji: '🕍', keywords: ['synagogue', 'vehicle'] },
      { emoji: '🛕', keywords: ['hindu temple', 'vehicle'] },
      { emoji: '🕋', keywords: ['kaaba', 'vehicle'] },
      { emoji: '⛩️', keywords: ['shinto shrine', 'vehicle'] },
      { emoji: '🛤️', keywords: ['railway track', 'vehicle'] },
      { emoji: '🛣️', keywords: ['road', 'vehicle'] },
      { emoji: '🗺️', keywords: ['world map', 'vehicle'] },
      { emoji: '🗿', keywords: ['moyai', 'vehicle'] },
      { emoji: '🗽', keywords: ['statue of liberty', 'vehicle'] },
      { emoji: '🗼', keywords: ['tokyo tower', 'vehicle'] },
      { emoji: '🏰', keywords: ['castle', 'vehicle'] },
      { emoji: '🏯', keywords: ['japanese castle', 'vehicle'] },
      { emoji: '🏟️', keywords: ['stadium', 'vehicle'] },
      { emoji: '🎡', keywords: ['carousel', 'vehicle'] },
      { emoji: '🎢', keywords: ['roller coaster', 'vehicle'] },
      { emoji: '🎠', keywords: ['carousel horse', 'vehicle'] },
      { emoji: '⛲', keywords: ['fountain', 'vehicle'] },
      { emoji: '⛱️', keywords: ['umbrella on ground', 'vehicle'] },
      { emoji: '🏖️', keywords: ['beach with umbrella', 'vehicle'] },
      { emoji: '🏝️', keywords: ['desert island', 'vehicle'] },
      { emoji: '🏔️', keywords: ['snow capped mountain', 'vehicle'] },
      { emoji: '🗻', keywords: ['mount fuji', 'vehicle'] },
      { emoji: '🌋', keywords: ['volcano', 'vehicle'] },
      { emoji: '🗾', keywords: ['japan flag', 'vehicle'] },
      { emoji: '🏕️', keywords: ['camping', 'vehicle'] },
      { emoji: '⛺', keywords: ['tent', 'vehicle'] },
      { emoji: '🏠', keywords: ['house', 'vehicle'] },
      { emoji: '🏡', keywords: ['house with garden', 'vehicle'] },
      { emoji: '🏘️', keywords: ['houses', 'vehicle'] },
      { emoji: '🏚️', keywords: ['empty house', 'vehicle'] },
      { emoji: '🏗️', keywords: ['building construction', 'vehicle'] },
      { emoji: '🏭', keywords: ['factory', 'vehicle'] },
      { emoji: '🏢', keywords: ['office building', 'vehicle'] },
      { emoji: '🏬', keywords: ['department store', 'vehicle'] },
      { emoji: '🏣', keywords: ['post office', 'vehicle'] },
      { emoji: '🏤', keywords: ['police station', 'vehicle'] },
      { emoji: '🏥', keywords: ['hospital', 'vehicle'] },
      { emoji: '🏦', keywords: ['bank', 'vehicle'] },
      { emoji: '🏨', keywords: ['hotel', 'vehicle'] },
      { emoji: '🏪', keywords: ['convenience store', 'vehicle'] },
      { emoji: '🏫', keywords: ['school', 'vehicle'] },
      { emoji: '🏩', keywords: ['love hotel', 'vehicle'] },
      { emoji: '💒', keywords: ['wedding', 'vehicle'] },
      { emoji: '⛪', keywords: ['church', 'vehicle'] },
      { emoji: '🕌', keywords: ['mosque', 'vehicle'] },
      { emoji: '🕍', keywords: ['synagogue', 'vehicle'] },
      { emoji: '🛕', keywords: ['hindu temple', 'vehicle'] },
      { emoji: '🕋', keywords: ['kaaba', 'vehicle'] },
      { emoji: '⛩️', keywords: ['shinto shrine', 'vehicle'] },
      { emoji: '🛤️', keywords: ['railway track', 'vehicle'] },
      { emoji: '🛣️', keywords: ['road', 'vehicle'] }
    ]
  },
  {
    name: 'Objects',
    icon: '💡',
    emojis: [
      { emoji: '💡', keywords: ['light bulb', 'object'] },
      { emoji: '🔦', keywords: ['flashlight', 'object'] },
      { emoji: '🕯️', keywords: ['candle', 'object'] },
      { emoji: '🪔', keywords: ['diya', 'object'] },
      { emoji: '🧯', keywords: ['fire extinguisher', 'object'] },
      { emoji: '🛢️', keywords: ['oil drum', 'object'] },
      { emoji: '💸', keywords: ['money bag', 'object'] },
      { emoji: '💵', keywords: ['dollar sign', 'object'] },
      { emoji: '💴', keywords: ['yen sign', 'object'] },
      { emoji: '💶', keywords: ['euro sign', 'object'] },
      { emoji: '💷', keywords: ['pound sign', 'object'] },
      { emoji: '🪙', keywords: ['coin', 'object'] },
      { emoji: '💰', keywords: ['money bag', 'object'] },
      { emoji: '💳', keywords: ['credit card', 'object'] },
      { emoji: '💎', keywords: ['gem stone', 'object'] },
      { emoji: '⚖️', keywords: ['balance scale', 'object'] },
      { emoji: '🪜', keywords: ['ladder', 'object'] },
      { emoji: '🧰', keywords: ['toolbox', 'object'] },
      { emoji: '🪛', keywords: ['wrench', 'object'] },
      { emoji: '🔧', keywords: ['hammer and wrench', 'object'] },
      { emoji: '🔨', keywords: ['hammer', 'object'] },
      { emoji: '⚒️', keywords: ['hammer and pick', 'object'] },
      { emoji: '🛠️', keywords: ['hammer and wrench', 'object'] },
      { emoji: '⛏️', keywords: ['pickaxe', 'object'] },
      { emoji: '🪚', keywords: ['carpentry saw', 'object'] },
      { emoji: '🔩', keywords: ['nut and bolt', 'object'] },
      { emoji: '⚙️', keywords: ['gear', 'object'] },
      { emoji: '🪤', keywords: ['mouse trap', 'object'] },
      { emoji: '🧲', keywords: ['magnet', 'object'] },
      { emoji: '⛓️', keywords: ['chains', 'object'] },
      { emoji: '🪝', keywords: ['hook', 'object'] },
      { emoji: '🧱', keywords: ['brick', 'object'] },
      { emoji: '🪞', keywords: ['mirror', 'object'] },
      { emoji: '🪟', keywords: ['window', 'object'] },
      { emoji: '🪑', keywords: ['seat', 'object'] }
    ]
  },
  {
    name: 'Symbols',
    icon: '❤️',
    emojis: [
      { emoji: '❤️', keywords: ['red', 'heart', 'love', 'romance', 'passion'] },
      { emoji: '🧡', keywords: ['orange', 'heart', 'love', 'warmth', 'friendship'] },
      { emoji: '💛', keywords: ['yellow', 'heart', 'love', 'joy', 'happiness'] },
      { emoji: '💚', keywords: ['green', 'heart', 'love', 'nature', 'growth'] },
      { emoji: '💙', keywords: ['blue', 'heart', 'love', 'trust', 'loyalty'] },
      { emoji: '💜', keywords: ['purple', 'heart', 'love', 'royalty', 'luxury'] },
      { emoji: '🖤', keywords: ['black', 'heart', 'love', 'dark', 'mystery'] },
      { emoji: '🤍', keywords: ['white', 'heart', 'love', 'purity', 'innocence'] },
      { emoji: '🤎', keywords: ['brown', 'heart', 'love', 'earth', 'stability'] },
      { emoji: '💔', keywords: ['broken', 'heart', 'sad', 'heartbreak', 'pain'] },
      { emoji: '❣️', keywords: ['heart', 'exclamation', 'love', 'emphasis', 'passion'] },
      { emoji: '💕', keywords: ['two', 'hearts', 'love', 'romance', 'couple'] },
      { emoji: '💞', keywords: ['revolving', 'hearts', 'love', 'romance', 'spinning'] },
      { emoji: '💓', keywords: ['beating', 'heart', 'love', 'life', 'pulse'] },
      { emoji: '💗', keywords: ['growing', 'heart', 'love', 'growth', 'development'] },
      { emoji: '💖', keywords: ['sparkling', 'heart', 'love', 'glitter', 'shine'] },
      { emoji: '💘', keywords: ['heart', 'arrow', 'love', 'cupid', 'romance'] },
      { emoji: '💝', keywords: ['heart', 'ribbon', 'love', 'gift', 'present'] },
      { emoji: '💟', keywords: ['heart', 'decoration', 'love', 'ornament', 'beauty'] },
      { emoji: '☮️', keywords: ['peace', 'symbol', 'harmony', 'tranquility', 'nonviolence'] },
      { emoji: '✝️', keywords: ['latin', 'cross', 'christianity', 'religion', 'faith'] },
      { emoji: '☪️', keywords: ['star', 'crescent', 'islam', 'religion', 'moon'] },
      { emoji: '🕉️', keywords: ['om', 'symbol', 'hinduism', 'religion', 'spirituality'] },
      { emoji: '☸️', keywords: ['wheel', 'dharma', 'buddhism', 'religion', 'karma'] },
      { emoji: '✡️', keywords: ['star', 'david', 'judaism', 'religion', 'jewish'] },
      { emoji: '🔯', keywords: ['six', 'pointed', 'star', 'religion', 'spirituality'] },
      { emoji: '🕎', keywords: ['menorah', 'candlestick', 'judaism', 'hanukkah', 'religion'] },
      { emoji: '☯️', keywords: ['yin', 'yang', 'balance', 'harmony', 'philosophy'] },
      { emoji: '☦️', keywords: ['orthodox', 'cross', 'christianity', 'religion', 'faith'] },
      { emoji: '🛐', keywords: ['place', 'worship', 'religion', 'prayer', 'spirituality'] },
      { emoji: '⛎', keywords: ['ophiuchus', 'zodiac', 'astrology', 'serpent', 'bearer'] },
      { emoji: '♈', keywords: ['aries', 'zodiac', 'astrology', 'ram', 'fire'] },
      { emoji: '♉', keywords: ['taurus', 'zodiac', 'astrology', 'bull', 'earth'] },
      { emoji: '♊', keywords: ['gemini', 'zodiac', 'astrology', 'twins', 'air'] },
      { emoji: '♋', keywords: ['cancer', 'zodiac', 'astrology', 'crab', 'water'] },
      { emoji: '♌', keywords: ['leo', 'zodiac', 'astrology', 'lion', 'fire'] },
      { emoji: '♍', keywords: ['virgo', 'zodiac', 'astrology', 'virgin', 'earth'] },
      { emoji: '♎', keywords: ['libra', 'zodiac', 'astrology', 'scales', 'air'] },
      { emoji: '♏', keywords: ['scorpio', 'zodiac', 'astrology', 'scorpion', 'water'] },
      { emoji: '♐', keywords: ['sagittarius', 'zodiac', 'astrology', 'archer', 'fire'] },
      { emoji: '♑', keywords: ['capricorn', 'zodiac', 'astrology', 'goat', 'earth'] },
      { emoji: '♒', keywords: ['aquarius', 'zodiac', 'astrology', 'water', 'bearer'] },
      { emoji: '♓', keywords: ['pisces', 'zodiac', 'astrology', 'fish', 'water'] },
      { emoji: '🆔', keywords: ['id', 'button', 'identification', 'identity', 'card'] },
      { emoji: '⚛️', keywords: ['atom', 'symbol', 'science', 'chemistry', 'physics'] },
      { emoji: '🉑', keywords: ['japanese', 'acceptable', 'button', 'ok', 'good'] },
      { emoji: '☢️', keywords: ['radioactive', 'symbol', 'danger', 'warning', 'nuclear'] },
      { emoji: '☣️', keywords: ['biohazard', 'symbol', 'danger', 'warning', 'biological'] },
      { emoji: '📴', keywords: ['mobile', 'phone', 'off', 'silent', 'quiet'] },
      { emoji: '📳', keywords: ['mobile', 'phone', 'vibration', 'mode', 'alert'] },
      { emoji: '🈶', keywords: ['japanese', 'not', 'free', 'of', 'charge', 'button'] },
      { emoji: '🈚', keywords: ['japanese', 'free', 'of', 'charge', 'button', 'complimentary'] },
      { emoji: '🈸', keywords: ['japanese', 'application', 'button', 'apply', 'request'] },
      { emoji: '🈺', keywords: ['japanese', 'open', 'for', 'business', 'button', 'available'] },
      { emoji: '🈷️', keywords: ['japanese', 'monthly', 'amount', 'button', 'month', 'cost'] },
      { emoji: '✴️', keywords: ['eight', 'pointed', 'star', 'sparkle', 'glitter'] },
      { emoji: '🆚', keywords: ['vs', 'button', 'versus', 'against', 'competition'] },
      { emoji: '💮', keywords: ['white', 'flower', 'japanese', 'grade', 'mark'] },
      { emoji: '🉐', keywords: ['japanese', 'bargain', 'button', 'deal', 'discount'] },
      { emoji: '㊙️', keywords: ['japanese', 'secret', 'button', 'confidential', 'private'] },
      { emoji: '㊗️', keywords: ['japanese', 'congratulations', 'button', 'celebration', 'congrats'] },
      { emoji: '🈴', keywords: ['japanese', 'passing', 'grade', 'button', 'success', 'pass'] },
      { emoji: '🈵', keywords: ['japanese', 'no', 'vacancy', 'button', 'full', 'occupied'] },
      { emoji: '🈹', keywords: ['japanese', 'discount', 'button', 'sale', 'reduced'] },
      { emoji: '🈲', keywords: ['japanese', 'prohibited', 'button', 'forbidden', 'banned'] },
      { emoji: '🅰️', keywords: ['a', 'button', 'blood', 'type', 'letter'] },
      { emoji: '🅱️', keywords: ['b', 'button', 'blood', 'type', 'letter'] },
      { emoji: '🆎', keywords: ['ab', 'button', 'blood', 'type', 'letters'] },
      { emoji: '🆑', keywords: ['cl', 'button', 'clear', 'letters', 'abbreviation'] },
      { emoji: '🅾️', keywords: ['o', 'button', 'blood', 'type', 'letter'] },
      { emoji: '🆘', keywords: ['sos', 'button', 'help', 'emergency', 'distress'] },
      { emoji: '❌', keywords: ['cross', 'mark', 'no', 'wrong', 'incorrect'] },
      { emoji: '⭕', keywords: ['hollow', 'red', 'circle', 'yes', 'correct'] },
      { emoji: '🛑', keywords: ['stop', 'sign', 'halt', 'traffic', 'road'] },
      { emoji: '⛔', keywords: ['no', 'entry', 'forbidden', 'prohibited', 'banned'] },
      { emoji: '📛', keywords: ['name', 'badge', 'identification', 'id', 'tag'] },
      { emoji: '🚫', keywords: ['prohibited', 'no', 'entry', 'forbidden', 'banned'] },
      { emoji: '💯', keywords: ['hundred', 'points', 'perfect', 'score', 'excellent'] },
      { emoji: '💢', keywords: ['anger', 'symbol', 'mad', 'angry', 'furious'] },
      { emoji: '♨️', keywords: ['hot', 'springs', 'bath', 'spa', 'relaxation'] },
      { emoji: '🚷', keywords: ['no', 'pedestrians', 'walking', 'forbidden', 'prohibited'] },
      { emoji: '🚯', keywords: ['no', 'littering', 'trash', 'forbidden', 'prohibited'] },
      { emoji: '🚳', keywords: ['no', 'bicycles', 'cycling', 'forbidden', 'prohibited'] },
      { emoji: '🚱', keywords: ['non', 'potable', 'water', 'drinking', 'forbidden'] },
      { emoji: '🔞', keywords: ['no', 'one', 'under', 'eighteen', 'adults', 'only'] },
      { emoji: '📵', keywords: ['no', 'mobile', 'phones', 'forbidden', 'prohibited'] },
      { emoji: '🚭', keywords: ['no', 'smoking', 'cigarettes', 'forbidden', 'prohibited'] },
      { emoji: '❗', keywords: ['exclamation', 'mark', 'emphasis', 'important', 'warning'] },
      { emoji: '❕', keywords: ['white', 'exclamation', 'mark', 'emphasis', 'important'] },
      { emoji: '❓', keywords: ['question', 'mark', 'question', 'inquiry', 'doubt'] },
      { emoji: '❔', keywords: ['white', 'question', 'mark', 'question', 'inquiry'] },
      { emoji: '‼️', keywords: ['double', 'exclamation', 'mark', 'emphasis', 'important'] },
      { emoji: '⁉️', keywords: ['exclamation', 'question', 'mark', 'surprise', 'confusion'] },
      { emoji: '🔅', keywords: ['low', 'brightness', 'dim', 'dark', 'light'] },
      { emoji: '🔆', keywords: ['high', 'brightness', 'bright', 'light', 'illumination'] },
      { emoji: '〽️', keywords: ['part', 'alternation', 'mark', 'music', 'repeat'] },
      { emoji: '⚠️', keywords: ['warning', 'sign', 'caution', 'danger', 'alert'] },
      { emoji: '🚸', keywords: ['children', 'crossing', 'kids', 'safety', 'caution'] },
      { emoji: '🔱', keywords: ['trident', 'emblem', 'weapon', 'poseidon', 'sea'] },
      { emoji: '⚜️', keywords: ['fleur', 'de', 'lis', 'symbol', 'royalty', 'nobility'] },
      { emoji: '🔰', keywords: ['japanese', 'symbol', 'for', 'beginner', 'novice', 'new'] },
      { emoji: '♻️', keywords: ['recycling', 'symbol', 'environment', 'green', 'eco'] }
    ]
  }
];

interface EmojiMenuProps {
  onEmojiSelect: (emoji: string) => void;
  trigger?: React.ReactNode;
  className?: string;
  position?: 'top' | 'bottom' | 'left' | 'right';
  align?: 'start' | 'center' | 'end';
}

export const EmojiMenu: React.FC<EmojiMenuProps> = ({
  onEmojiSelect,
  trigger,
  className,
  position = 'top',
  align = 'center'
}) => {
  const [isOpen, setIsOpen] = useState(false);
  const [searchQuery, setSearchQuery] = useState('');
  const [selectedCategory, setSelectedCategory] = useState(0);
  const searchInputRef = useRef<HTMLInputElement>(null);

  // Filter emojis based on search query
  const filteredEmojis = emojiCategories.map(category => ({
    ...category,
    emojis: category.emojis.filter(emoji => 
      emoji.emoji.includes(searchQuery) || 
      emoji.keywords.some(keyword => keyword.includes(searchQuery.toLowerCase())) || 
      category.name.toLowerCase().includes(searchQuery.toLowerCase())
    )
  })).filter(category => category.emojis.length > 0);

  // Handle emoji selection
  const handleEmojiClick = (emoji: string) => {
    onEmojiSelect(emoji);
    setIsOpen(false);
    setSearchQuery('');
  };

  // Handle keyboard navigation
  useEffect(() => {
    if (isOpen && searchInputRef.current) {
      searchInputRef.current.focus();
    }
  }, [isOpen]);

  // Handle escape key to close
  useEffect(() => {
    const handleEscape = (e: KeyboardEvent) => {
      if (e.key === 'Escape' && isOpen) {
        setIsOpen(false);
      }
    };

    document.addEventListener('keydown', handleEscape);
    return () => document.removeEventListener('keydown', handleEscape);
  }, [isOpen]);

  // Handle global keyboard shortcut to open
  useEffect(() => {
    const handleKeydown = (e: KeyboardEvent) => {
      if (e.key === ':' && e.ctrlKey) {
        e.preventDefault();
        setIsOpen(true);
      }
    };

    document.addEventListener('keydown', handleKeydown);
    return () => document.removeEventListener('keydown', handleKeydown);
  }, []);

  return (
    <Popover open={isOpen} onOpenChange={setIsOpen}>
      <PopoverTrigger asChild>
        {trigger || (
          <Button
            variant="ghost"
            size="icon"
            className={cn("h-8 w-8", className)}
          >
            <Smile className="h-4 w-4" />
          </Button>
        )}
      </PopoverTrigger>
      <PopoverContent 
        className="bg-background w-80 p-0" 
        align={align}
        side={position}
      >
        <div className="p-3 border-b">
          <div className="relative">
            <Search className="absolute left-3 top-1/2 transform -translate-y-1/2 h-4 w-4 text-muted-foreground" />
            <Input
              ref={searchInputRef}
              placeholder="Search emojis..."
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
              className="pl-9"
            />
          </div>
        </div>

        {/* Category tabs */}
        {!searchQuery && (
          <div className="flex border-b overflow-x-auto">
            {emojiCategories.map((category, index) => (
              <button
                key={category.name}
                onClick={() => setSelectedCategory(index)}
                className={cn(
                  "flex-shrink-0 px-3 py-2 text-sm font-medium border-b-2 transition-colors cursor-pointer",
                  selectedCategory === index
                    ? "border-primary text-primary"
                    : "border-transparent text-muted-foreground hover:text-foreground"
                )}
              >
                <span>{category.icon}</span>
              </button>
            ))}
          </div>
        )}

        {/* Emoji grid */}
        <ScrollArea className="h-64">
          <div className="p-3">
            {searchQuery ? (
              // Search results
              <div className="grid grid-cols-8 gap-2">
                {filteredEmojis.flatMap(category => 
                  category.emojis.map((emoji, index) => (
                    <button
                      key={`${category.name}-${index}`}
                      onClick={() => handleEmojiClick(emoji.emoji)}
                      className="w-8 h-8 text-lg hover:bg-accent rounded transition-colors flex items-center justify-center"
                      title={emoji.emoji}
                    >
                      {emoji.emoji}
                    </button>
                  ))
                )}
              </div>
            ) : (
              // Category view
              <div className="grid grid-cols-8 gap-2">
                {emojiCategories[selectedCategory]?.emojis.map((emoji, index) => (
                  <button
                    key={index}
                    onClick={() => handleEmojiClick(emoji.emoji)}
                    className="w-8 h-8 text-lg hover:bg-accent rounded transition-colors flex items-center justify-center"
                    title={emoji.emoji}
                  >
                    {emoji.emoji}
                  </button>
                ))}
              </div>
            )}
          </div>
        </ScrollArea>
      </PopoverContent>
    </Popover>
  );
};

export default EmojiMenu; 